# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Inputs'
on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board'
        required: true
      shield:
        description: 'Shield'
        required: false
        default: 'default'
      alphas:
        description: 'Miryoku Alphas'
        required: false
        default: 'default'
      nav:
        description: 'Miryoku Nav'
        required: false
        default: 'default'
      clipboard:
        description: 'Miryoku Clipboard'
        required: false
        default: 'default'
      layers:
        description: 'Miryoku Layers'
        required: false
        default: 'default'
      mapping:
        description: 'Miryoku Mapping'
        required: false
        default: 'default'
      kconfig:
        description: 'Kconfig'
        required: false
        default: 'default'
jobs:
  process-inputs:
    runs-on: ubuntu-latest
    outputs:
      board: ${{ steps.process-inputs.outputs.board }}
      shield: ${{ steps.process-inputs.outputs.shield }}
      alphas: ${{ steps.process-inputs.outputs.alphas }}
      nav: ${{ steps.process-inputs.outputs.nav }}
      clipboard: ${{ steps.process-inputs.outputs.clipboard }}
      layers: ${{ steps.process-inputs.outputs.layers }}
      mapping: ${{ steps.process-inputs.outputs.mapping }}
      kconfig: ${{ steps.process-inputs.outputs.kconfig }}
    steps:
      - name: Process inputs
        id: process-inputs
        run: |
          set-output()
          {
            json=`echo "$2" | jq -cnR 'inputs | split("(,| )+";"")'`
            echo "::set-output name=$1::$json"
          }
          set-output "board" "${{ github.event.inputs.board }}"
          set-output "shield" "${{ github.event.inputs.shield }}"
          set-output "alphas" "${{ github.event.inputs.alphas }}"
          set-output "nav" "${{ github.event.inputs.nav }}"
          set-output "clipboard" "${{ github.event.inputs.clipboard }}"
          set-output "layers" "${{ github.event.inputs.layers }}"
          set-output "mapping" "${{ github.event.inputs.mapping }}"
          set-output "kconfig" "${{ github.event.inputs.kconfig }}"
  build:
    uses: manna-harbour/zmk-config/.github/workflows/main.yml@82f608118a663f0cb02a3cfa4330e21d58b52a4f
    needs: process-inputs
    with:
      board: ${{ needs.process-inputs.outputs.board }}
      shield: ${{ needs.process-inputs.outputs.shield }}
      alphas: ${{ needs.process-inputs.outputs.alphas }}
      nav: ${{ needs.process-inputs.outputs.nav }}
      clipboard: ${{ needs.process-inputs.outputs.clipboard }}
      layers: ${{ needs.process-inputs.outputs.layers }}
      mapping: ${{ needs.process-inputs.outputs.mapping }}
      kconfig: ${{ needs.process-inputs.outputs.kconfig }}
