name: Build
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: zmkfirmware/zmk-build-arm:2.4
    strategy:
      fail-fast: false
      matrix:
        config:
          - ""
        board:
          - nice_nano
        shield:

#          - bfo9000_left
#          - bfo9000_right

          - corne_left
          - corne_right

          - cradio_left
          - cradio_right

#          - cradio36_left
#          - cradio36_right

#          - cradios_left
#          - cradios_right

#          - cradioz_left
#          - cradioz_right

          - crbn

          - eek

          - helix_left
          - helix_right

          - iris_left
          - iris_right

          - jian_left
          - jian_right

          - jorne_left
          - jorne_right

          - kyria_left
          - kyria_right

          - lily58_left
          - lily58_right

          - microdox_left
          - microdox_right

          - sofle_left
          - sofle_right

          - splitreus62_left
          - splitreus62_right

        include:

#          - shield: absolem
#            board: 

#          - board: ahokore

#          - board: ferris

          - board: planck_rev6

          - config: clipboard_mac
            board: nice_nano
            shield: corne_left

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            bootloader/
            modules/
            tools/
            zephyr/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: Initialize workspace (west init)
        run: west init -l config
      - name: Update modules (west update)
        run: west update
      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export
      - name: Prepare variables
        id: variables
        run: |
          ARTIFACT_NAME="Miryoku-ZMK"
          if [ -n "${{ matrix.shield }}" ]; then
            SHIELD_ARG="-DSHIELD=${{ matrix.shield }}"
            ARTIFACT_NAME="$ARTIFACT_NAME-${{ matrix.shield }}-${{ matrix.board }}"
          else
            SHIELD_ARG=
            ARTIFACT_NAME="$ARTIFACT_NAME-${{ matrix.board }}"
          fi
          if [ -n "${{ matrix.config }}" ]; then
            ARTIFACT_NAME="$ARTIFACT_NAME-${{ matrix.config }}"
          fi
          echo ::set-output name=shield-arg::${SHIELD_ARG}
          echo ::set-output name=artifact-name::${ARTIFACT_NAME}
          ARTIFACTS_DIR=artifacts
          echo "::set-output name=artifacts-dir::$ARTIFACTS_DIR"
      - name: Copy config file
        run: |
          if [ -n "${{ matrix.config }}" ]; then
            cp "${GITHUB_WORKSPACE}/miryoku/configs/${{ matrix.config }}.h" "${GITHUB_WORKSPACE}/miryoku/config.h"
          fi
      - name: Build (west build)
        run: west build -s zmk/app -b ${{ matrix.board }} -- ${{ steps.variables.outputs.shield-arg }}
          -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Prepare artifacts
        run: |
          mkdir ${{ steps.variables.outputs.artifacts-dir }}
          if [ -n "${{ matrix.config }}" ]; then
            cp "${GITHUB_WORKSPACE}/miryoku/config.h" ${{ steps.variables.outputs.artifacts-dir }}
          fi
          basename="build/zephyr/zmk"
          for extension in "hex" "uf2"
          do
            file="$basename.$extension"
            if [ -f "$file" ]
            then
              cp "$file" "${{ steps.variables.outputs.artifacts-dir }}/${{ steps.variables.outputs.artifact-name }}.$extension"
            fi
          done
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.variables.outputs.artifact-name }}
          path: |
             ${{ steps.variables.outputs.artifacts-dir }}
        continue-on-error: true



# todo: 
# remove _left and _right from artifact dir and put at the end of artifact filename
# fix Array
