# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Configs'
on:
  - workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: manna-harbour/zmk-config/.github/workflows/main.yml@82f608118a663f0cb02a3cfa4330e21d58b52a4f
    with:
      board: '["nice_nano"]'
      shield: '["corne_left"]'
      alphas: '["default","azerty","beakl15","colemak","colemakdhk","dvorak","halmak","workman","qwerty","qwertz"]'
      nav: '["default","vi","invertedt"]'
      clipboard: '["default","fun","mac","win"]'
      layers: '["default","flip"]'
