# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Configs'
on:
  - workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: manna-harbour/zmk-config/.github/workflows/main.yml@31a649e5571b4572d7010561dd3f191922cd9410
    with:
      board: '["nice_nano"]'
      shield: '["corne_left"]'
      alphas: '[
        "default",
        "azerty",
        "beakl15",
        "colemak",
        "colemakdhk",
        "dvorak",
        "halmak",
        "qwerty",
        "qwertz"
        "workman",
      ]'
      nav: '[
        "default",
        "invertedt"
        "vi",
      ]'
      clipboard: '[
        "default",
        "fun",
        "mac",
        "win"
      ]'
      layers: '[
        "default",
        "flip"
      ]'
