# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Promicro Controllers'
on:
  - workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: manna-harbour/zmk-config/.github/workflows/main.yml@31a649e5571b4572d7010561dd3f191922cd9410
    with:
      board: '["bluemicro840_v1","mikoto_520","nice_nano","nice_nano_v2","nrfmicro_11","nrfmicro_13","proton_c"]'
      shield: '["corne_left"]'
