# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test All Boards'
on: workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'manna-harbour'
    uses: ./.github/workflows/main.yml
    with:
      board: '[
        "ahokore",
        "ble_chiffre",
        "corne-ish_zen_left","corne-ish_zen_right",
        "ferris_rev02",
        "ffkb-holyiot",
        "klacker_bs",
        "one42",
        "planck_rev6",
        "preonic_rev3",
        "technikable",
        "tipper_tf",
        "zaphod"
      ]'

